name: deploy
on:
  push:
    branches:
      - main
jobs: 
  fetchandbuild:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "20.x"
        - run: pnpm install
        - run: pnpm build
        - uses: JamesIves/github-pages-deploy-action@4.1.7
          with:
            branch: page
            folder: dist