name: update
on:
  workflow_dispatch:
    inputs:
      date:
        description: 'date'
        required: true
        type: string
      detail:
        description: 'detail'
        type: string
        required: true
permissions:
  contents: write
jobs: 
  recievedata:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: "20.x"
        - run: node scripts/updateDataFromAction.js ${{ inputs.date }} ${{ inputs.detail }}