name: update
on:
  workflow_dispatch:
    inputs:
      date:
        description: "date"
        required: true
        type: string
      detail:
        description: "detail"
        type: string
        required: true
permissions:
  contents: write
jobs:
  recievedataandpushchange:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          GH_TOKEN: ${{ secrets.PUSH_SECRET }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - env:
          GH_TOKEN: ${{ secrets.PUSH_SECRET }}
        run: |
          yarn
          node scripts/updateDataFromAction.js ${{ inputs.date }} ${{ inputs.detail }}
          git commit -a -m "action: update data"
          git push origin main